### ISSUE TITLE
Create a workflow for pip

### ISSUE THREAD

**Issue by magoorden** [mihsamusev/strategoutil#5]

**Comment by mihsamusev** [comment]
This action might help
https://github.com/marketplace/actions/pypi-publish

Logic could be:
if the commit is pushed to master and it is tagged and the version in `setup` file does not exists on pypi => build wheels + upload

this will ensure that what you get by `pip install strategoutil` and what you see in master branch are identical

**Comment by mihsamusev** [comment]
Some tricks of how to trigger one workflow after another
https://stevenmortimer.com/running-github-actions-sequentially/
Useful because we only want to push after all tests have passed

**Comment by mihsamusev** [comment]
Solved in https://github.com/mihsamusev/strategoutil/pull/10
